name: Generate design tokens

permissions:
  contents: write  # Permite escrever no conteúdo (fazer push)  
  
on:
  repository_dispatch:
    types: update-tokens

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Cria uma nova branch com base na branch principal (main)
      - name: Create a new branch
        run: |
          git checkout -b "update-tokens"

      # Empurra a nova branch para o repositório remoto
      - name: Push the new branch
        run: |
          git push origin "update-tokens"

      # Cria o JSON com o nome correto: input/tokens.json
      - name: Create input JSON
        id: create-json
        uses: jsdaniell/create-json@1.1.2
        with:
          name: tokens.json
          json: ${{ github.event.client_payload.tokens }}
          dir: "input"

      # Exibe o conteúdo do arquivo JSON correto
      - name: Display design tokens
        run: cat input/tokens.json

      # Outras etapas (como instalação do Node.js, dependências, build, etc)
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      # Configura a identidade do Git
      - name: Configure Git user
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      # Garantindo que as referências do repositório estejam atualizadas
      - name: Fetch all branches
        run: |
          git fetch --all