name: Generate design tokens

permissions:
  contents: write # Permite escrever no conteúdo (fazer push)

on:
  repository_dispatch:
    types: update-tokens

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Faz checkout do repositório diretamente para a branch main
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: main  # Garante que estamos na branch 'main'

      # Cria o JSON com o nome correto: input/tokens.json
      - name: Create input JSON
        id: create-json
        uses: jsdaniell/create-json@1.1.2
        with:
          name: tokens.json
          json: ${{ github.event.client_payload.tokens }}
          dir: "input"

      # Exibe o conteúdo do arquivo JSON correto
      - name: Display design tokens
        run: cat input/tokens.json

      # Configura a identidade do Git
      - name: Configure Git user
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      # Comita o arquivo de tokens.json atualizado (somente se houver alterações) diretamente na branch main
      - name: Commit updated tokens.json to main
        run: |
          git status
          git add input/tokens.json
          git commit -m "update: Refresh design tokens" || echo "No changes to commit"
          git push origin main

      # Outras etapas (como instalação do Node.js, dependências, build, etc)
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      # Execute a ferramenta de transformação de tokens para gerar CSS
      - name: Generate CSS from tokens
        run: |
          # Aqui, executamos o comando que gera o CSS usando o config.json
          npx style-dictionary build --config config.json

      - name: Build CSS
        run: npm run build

      # Garantindo que as referências do repositório estejam atualizadas
      - name: Fetch all branches
        run: |
          git fetch --all
