name: Generate design tokens

on:
  repository_dispatch:
    types: update-tokens

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3

      # Setup Node.js to match the local version
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.12.0'  # Atualizado para v22.12.0

      # Validate Node.js version
      - name: Check Node.js Version
        run: node --version

      # Install dependencies using npm ci
      - name: Install dependencies
        run: npm ci

      # Downgrade zip.js (if necessary)
      - name: Downgrade zip.js
        run: npm install @zip.js/zip.js@2.0.27

      # Verify dependencies
      - name: List Installed Packages
        run: npm list

      # Run the build process
      - name: Build
        run: npm run build

      # Create a pull request
      - name: Create PR
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "style: Update design tokens"
          title: ${{ github.event.client_payload.commitMessage || 'Update design tokens' }}
          body: "Design tokens have been updated via Figma and need to be reviewed."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: "main"