name: Generate design tokens

on:
  repository_dispatch:
    types: update-tokens

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Check Node.js Version
        run: node --version

      - name: Install dependencies
        run: npm ci

      - name: Install web-streams-polyfill
        run: npm install web-streams-polyfill

      - name: Downgrade zip.js
        run: npm install @zip.js/zip.js@2.0.27

      - name: Build
        run: npm run build

      - name: Create PR
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "style: Update design tokens"
          title: ${{ github.event.client_payload.commitMessage || 'Update design tokens' }}
          body: "Design tokens have been updated via Figma and need to be reviewed."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: "main"