name: Generate design tokens

permissions:
  contents: write # Permite escrever no conteúdo (fazer push)

on:
  repository_dispatch:
    types: update-tokens

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Faz checkout do repositório diretamente para a branch update-tokens
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Verifica e cria a branch 'update-tokens' se não existir
      - name: Create branch update-tokens
        run: |
          git checkout --orphan update-tokens
          git reset --hard
          git push -u origin update-tokens

      # Cria o JSON com o nome correto: input/tokens.json
      - name: Create input JSON
        id: create-json
        uses: jsdaniell/create-json@1.1.2
        with:
          name: tokens.json
          json: ${{ github.event.client_payload.tokens }}
          dir: "input"

      # Exibe o conteúdo do arquivo JSON correto
      - name: Display design tokens
        run: cat input/tokens.json

      # Configura a identidade do Git
      - name: Configure Git user
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      # Comita o arquivo de tokens.json atualizado (somente se houver alterações) diretamente na branch update-tokens
      - name: Commit updated tokens.json to update-tokens
        run: |
          git status
          git add input/tokens.json
          git commit -m "update: Refresh design tokens" || echo "No changes to commit"
          git push origin update-tokens

      # Instala o Node.js
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      # Instala as dependências (usando npm ci)
      - name: Install dependencies
        run: npm ci

      # Verificar se o Style Dictionary está instalado
      - name: Verify Style Dictionary installation
        run: |
          if ! npm list style-dictionary; then
            echo "Style Dictionary is not installed!"
            exit 1
          else
            echo "Style Dictionary is installed!"
          fi

      # Executa diretamente o comando de build do style-dictionary
      - name: Generate CSS from tokens
        run: |
          npx style-dictionary build # Executa diretamente o comando para garantir que o build seja feito

      # Commit e push dos arquivos gerados
      - name: Commit generated files to GitHub
        run: |
          git add build/css/variables.css build/js/variables.js
          git commit -m "build: Generated CSS and JS tokens" || echo "No changes to commit"
          git push origin update-tokens

      # Garantindo que as referências do repositório estejam atualizadas
      - name: Fetch all branches
        run: |
          git fetch --all
