name: Generate design tokens

permissions:
  contents: write  # Permite escrever no conteúdo (fazer push)

on:
  repository_dispatch:
    types: update-tokens

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Cria uma nova branch com base na branch principal (main)
      - name: Create a new branch
        run: |
          git checkout -b "update-tokens"

      # Cria o JSON com o nome correto: input/tokens.json
      - name: Create input JSON
        id: create-json
        uses: jsdaniell/create-json@1.1.2
        with:
          name: tokens.json
          json: ${{ github.event.client_payload.tokens }}
          dir: "input"

      # Exibe o conteúdo do arquivo JSON correto
      - name: Display design tokens
        run: cat input/tokens.json

      # Comita o arquivo de tokens.json atualizado
      - name: Commit updated tokens.json
        run: |
          git add input/tokens.json
          git commit -m "update: Refresh design tokens"
          git push origin "update-tokens"

      # Outras etapas (como instalação do Node.js, dependências, build, etc)
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      # Configura a identidade do Git
      - name: Configure Git user
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      # Garantindo que as referências do repositório estejam atualizadas
      - name: Fetch all branches
        run: |
          git fetch --all
          
      # Criação da Pull Request (sem commit, apenas PR)
      - name: Create PR
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: "style: Update design tokens"
          title: ${{ github.event.client_payload.commitMessage || 'Update design tokens' }}
          body: "Design tokens have been updated via Figma and need to be reviewed."
          branch: "update-tokens"  # Branch nova de origem dos dados
          base: main               # Branch de destino
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}