name: Generate design tokens

permissions:
  contents: write # Permite escrever no conteúdo (fazer push)

on:
  repository_dispatch:
    types: update-tokens

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Faz checkout do repositório diretamente para a branch main
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: main  # Garante que estamos na branch 'main'

      # Cria o JSON com o nome correto: input/tokens.json
      - name: Create input JSON
        id: create-json
        uses: jsdaniell/create-json@1.1.2
        with:
          name: tokens.json
          json: ${{ github.event.client_payload.tokens }}
          dir: "input"

      # Exibe o conteúdo do arquivo JSON correto
      - name: Display design tokens
        run: cat input/tokens.json

      # Configura a identidade do Git
      - name: Configure Git user
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      # Comita o arquivo de tokens.json atualizado (somente se houver alterações) diretamente na branch main
      - name: Commit updated tokens.json to main
        run: |
          git status
          git add input/tokens.json
          git commit -m "update: Refresh design tokens" || echo "No changes to commit"
          git push origin main

      # Instala o Node.js
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      # Instala as dependências (usando npm ci)
      - name: Install dependencies
        run: npm ci
        
      # Verificar se o Style Dictionary está instalado
      - name: Verify Style Dictionary installation
        run: |
          if ! npm list style-dictionary; then
            echo "Style Dictionary is not installed!"
            exit 1
          else
            echo "Style Dictionary is installed!"
          fi

      # Exibe a estrutura de diretórios antes do build para diagnóstico
      - name: Display directory structure before build
        run: |
          echo "Diretório antes do build:"
          ls -R

      # Executa diretamente o comando de build do style-dictionary
      - name: Generate CSS from tokens
        run: |
          npx style-dictionary build  # Executa diretamente o comando para garantir que o build seja feito

      # Exibe a estrutura de diretórios após o build para verificar o arquivo gerado
      - name: Display directory structure after build
        run: |
          echo "Diretório após o build:"
          ls -R

      # Verifica se o CSS foi gerado corretamente
      - name: Verify CSS output
        run: |
          ls build/css/  # Verifica se o arquivo 'variables.css' foi gerado corretamente
      
      # Commit e push dos arquivos gerados
      - name: Commit generated files to GitHub
        run: |
          git add build/css/variables.css build/js/variables.js
          git commit -m "build: Generated CSS and JS tokens"
          git push origin main
          
      # Garantindo que as referências do repositório estejam atualizadas
      - name: Fetch all branches
        run: |
          git fetch --all
